/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Interface.inReceiveMessage;
import static Client.LoginForm.user;
import Model.Game;
import Model.KMessage;

import java.io.IOException;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class GameForm extends javax.swing.JFrame implements inReceiveMessage {

    static ListenServer listenServer = null;
    DefaultListModel<String> model = new DefaultListModel<>();
    ArrayList<Question> questions;
    static Game game;
    static Game game2;
    static int dem = 0;

    public GameForm(ListenServer listenServer) {
        initComponents();
        setLocationRelativeTo(null);
        this.listenServer = listenServer;
        this.listenServer.receive = this;
        questions = new ArrayList<>();
        try {
            listenServer.SendMessage(40, null);
        } catch (IOException ex) {
            Logger.getLogger(GameForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbQues1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lbQues2 = new javax.swing.JLabel();
        lbQues3 = new javax.swing.JLabel();
        lbQues4 = new javax.swing.JLabel();
        lbQues5 = new javax.swing.JLabel();
        cbAns1 = new javax.swing.JComboBox<>();
        cbAns2 = new javax.swing.JComboBox<>();
        cbAns3 = new javax.swing.JComboBox<>();
        cbAns4 = new javax.swing.JComboBox<>();
        cbAns5 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("CÂU 1:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("CÂU 2:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("CÂU 3:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("CÂU 4:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("CÂU 5:");

        lbQues1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbQues1.setText("jLabel10");

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lbQues2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbQues2.setText("jLabel6");

        lbQues3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbQues3.setText("jLabel6");

        lbQues4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbQues4.setText("jLabel6");

        lbQues5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbQues5.setText("jLabel6");

        cbAns1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbAns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAns1ActionPerformed(evt);
            }
        });

        cbAns2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbAns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAns2ActionPerformed(evt);
            }
        });

        cbAns3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbAns3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAns3ActionPerformed(evt);
            }
        });

        cbAns4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbAns4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAns4ActionPerformed(evt);
            }
        });

        cbAns5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbAns5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAns5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("ĐÁP ÁN: ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("ĐÁP ÁN: ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("ĐÁP ÁN: ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("ĐÁP ÁN: ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("ĐÁP ÁN: ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("CHỌN ĐÁP ÁN ĐÚNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbQues5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbAns5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbAns1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbAns3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbAns4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbAns2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(2, 2, 2)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(lbQues4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(lbQues3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(lbQues2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(lbQues1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel11)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbQues1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbQues2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbAns2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbQues3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAns3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbQues4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAns4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbQues5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAns5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbQues1.getAccessibleContext().setAccessibleName("lbQues1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAns1ActionPerformed

    private void cbAns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAns2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAns2ActionPerformed

    private void cbAns3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAns3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAns3ActionPerformed

    private void cbAns4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAns4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAns4ActionPerformed

    private void cbAns5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAns5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAns5ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (cbAns1.getSelectedIndex() == questions.get(0).getCorrectAnswer()) {
            dem++;
        }
        if (cbAns2.getSelectedIndex() == questions.get(1).getCorrectAnswer()) {
            dem++;
        }
        if (cbAns3.getSelectedIndex() == questions.get(2).getCorrectAnswer()) {
            dem++;
        }
        if (cbAns4.getSelectedIndex() == questions.get(3).getCorrectAnswer()) {
            dem++;
        }
        if (cbAns5.getSelectedIndex() == questions.get(4).getCorrectAnswer()) {
            dem++;
        }

        LocalTime time = java.time.LocalTime.now();
        result(dem, time);
      
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameForm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cbAns1;
    private javax.swing.JComboBox<String> cbAns2;
    private javax.swing.JComboBox<String> cbAns3;
    private javax.swing.JComboBox<String> cbAns4;
    private javax.swing.JComboBox<String> cbAns5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbQues1;
    private javax.swing.JLabel lbQues2;
    private javax.swing.JLabel lbQues3;
    private javax.swing.JLabel lbQues4;
    private javax.swing.JLabel lbQues5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ReceiveMessage(KMessage msg) throws IOException {
        switch (msg.getType()) {
            // Nhận yêu cầu chơi 
            case 41: {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "Sẵn sàng chơi?", "Title on Box", dialogButton);
                if (dialogResult == 0) {
                    listenServer.SendMessage(44, null);// Gửi chấp nhận
                } else {
                    listenServer.SendMessage(45, null);// Gửi từ chối 
                }
                break;
            }
            // Người chơi đồng ý và nhận dự liệu
            case 46: {
                questions = msg.getQuestions();// Nhận câu hỏi
                setQuestion();
                break;
            }
            // Người chơi không đồng ý
            case 47: {
                JOptionPane.showMessageDialog(null, "Người chơi không đồng ý!", "Message", 1);
                break;
            }
            case 60: {
                game2 = (Game) msg.getObject();
                String t = "Hòa";
                JOptionPane.showMessageDialog(null, "Hòa!", "Message", 1);
                this.setVisible(false);
                ResultForm resultForm = new ResultForm(listenServer, game2, t);
                resultForm.setVisible(true);
                break;
            }
            // Thông báo thắng
            case 61: {
                game2 = (Game) msg.getObject();
                JOptionPane.showMessageDialog(null, "Thắng!", "Message", 1);
                String t = "Thắng";
                this.setVisible(false);
                ResultForm resultForm = new ResultForm(listenServer, game2, t);
                resultForm.setVisible(true);
                break;
            }
            // Thông báo thua
            case 62: {
                game2 = (Game) msg.getObject();
                String t = "Thua";
                JOptionPane.showMessageDialog(null, "Thua!", "Message", 1);
                this.setVisible(false);
                ResultForm resultForm = new ResultForm(listenServer, game2, t);
                resultForm.setVisible(true);
                break;
            }
            // Thông báo người chơi thoát khỏi phòng và out phòng
            case 71: {
                JOptionPane.showMessageDialog(null, "Nguoi choi da thoat khoi phong!", "Message", 1);
                this.setVisible(false);
                HomeForm homeForm = new HomeForm(listenServer);
                homeForm.setVisible(true);
                break;
            }
            case 100: {
                JOptionPane.showMessageDialog(null, "Đối thủ chưa hoàn thành trận đấu!", "Message", 1);
                break;
            }
        }
    }

    private void setQuestion() {
        //lấy câu hỏi
        lbQues1.setText(questions.get(0).getQuestion());
        lbQues2.setText(questions.get(1).getQuestion());
        lbQues3.setText(questions.get(2).getQuestion());
        lbQues4.setText(questions.get(3).getQuestion());
        lbQues5.setText(questions.get(4).getQuestion());
      
         cbAns1.removeAllItems();
          cbAns2.removeAllItems();
          cbAns3.removeAllItems();
          cbAns4.removeAllItems();
          cbAns5.removeAllItems();
       
        //lấy đáp án
        cbAns1.addItem(questions.get(0).getAnswerA());
        cbAns1.addItem(questions.get(0).getAnswerB());
        cbAns1.addItem(questions.get(0).getAnswerC());
        cbAns1.addItem(questions.get(0).getAnswerD());

        cbAns2.addItem(questions.get(1).getAnswerA());
        cbAns2.addItem(questions.get(1).getAnswerB());
        cbAns2.addItem(questions.get(1).getAnswerC());
        cbAns2.addItem(questions.get(1).getAnswerD());

        cbAns3.addItem(questions.get(2).getAnswerA());
        cbAns3.addItem(questions.get(2).getAnswerB());
        cbAns3.addItem(questions.get(2).getAnswerC());
        cbAns3.addItem(questions.get(2).getAnswerD());

        cbAns4.addItem(questions.get(3).getAnswerA());
        cbAns4.addItem(questions.get(3).getAnswerB());
        cbAns4.addItem(questions.get(3).getAnswerC());
        cbAns4.addItem(questions.get(3).getAnswerD());

        cbAns5.addItem(questions.get(4).getAnswerA());
        cbAns5.addItem(questions.get(4).getAnswerB());
        cbAns5.addItem(questions.get(4).getAnswerC());
        cbAns5.addItem(questions.get(4).getAnswerD());

         
    }

    private void result(int dem, LocalTime time) {
        //jLabel1.setText("Số câu đúng: " + dem);
        game = new Game(dem, time, user);
        try {
            listenServer.SendMessage(50, game);
        } catch (IOException ex) {
            Logger.getLogger(GameForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
